- hosts: test
  tasks:
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: remove apache2 package
    apt:
      name: apache2
      state: absent
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: remove docker.io and docker-compose
    apt:
      name: [docker.io,docker-compose] 
      state: absent
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
