---
- hosts: all
  become: yes
  tasks:
    - name: ensure NTP is installed
      yum: name=ntp state=present
    - name: ensure NTP is running
      service: name=ntpd state=started enabled=yes
        