- hosts: test,centos
  tasks:
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: install docker.io and docker-compose
    apt:
      name: [docker.io,docker-compose] 
      state: latest
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

##########################
  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: install apache2 and php package
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'