---
- hosts: ubu_node_01
  become: true
  tasks:
  - name: Install Package
    apt: name=apache2 state=present
    notify:
    - Start apache2
  handlers:
  - name: Start apache2
    service: name=apache2 state=started