---
- name: Backup Linux user home directories
  hosts: all
  tasks:
# TASK 1
  - name: Create a directory for backups
    file:
      path: /var/bkpspool
      state: directory
#TASK 2
  - name: Retrieve the list of home directories
    command: ls /home
    register: home_dirs
#TASK 3
  - name: add home directories in Backup folder
    file:
      path: /var/bkpspool/{{item}}
      src: /home/{{item}}
      state: link
    with_items: "{{home_dirs.stdout_lines}}"