---
- hosts: all
  become: yes
  tasks:
  - name: "shut down CentOS 6 systems"
    command: /sbin/shutdown -t now
    when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "6"