---
- hosts: all
  become: yes
  tasks:
#Below script will install apache2 on Debian and ignore centos hosts
  - name: Install apache2 on Ubuntu machines
    apt: 
      name: apache2 
      state: latest
    when: ansible_os_family == "Debian"
    register: apt_output
  - name: Display the console output
    debug: var=apt_output
#Below script will install httpd on centos and ignore ubuntu hosts
  - name: Install httpd on centos machines
    yum: 
      name: httpd 
      state: latest
    when: ansible_os_family == "RedHat"
    register: yum_output
  - name: Display the console output
    debug: var=yum_output